####################################################################################
#programadora: Helen Garcia                                                        #
#e-mail: garcia.helen14@yahoo.com.ar                                               #
#celular: 156379648                                                                #
####################################################################################
#fecha:04/08/2022
#lenguaje:python
#version:3.10.4
#curso: programacion python en ADAITW

#objetivo:Crear un programa que pida al usuario ingresar
#  el valor de la base y el valor de la altura de un triangulo,
#  calcular su área y mostrarlo en un mensaje.


b= int(input("Ingrese el valor para la base del triangulo: "))
a= int(input("Ingrese el valor para la altura del triangulo: "))
area = (b * a) / 2
print("el area del triangulo es" , area )