#programadora: helen garcia
#curso: programacion ada
#lenguaje: python
#version : 3.10.4

#objetivo: Crear un programa que pida al usuario ingresar, por separado, tres gustos de helado,
#y luego muestre un mensaje que diga, por ejemplo, "Aquí tiene su helado de chocolate, dulce de leche y menta granizada".


helado1= input("ingrese su primer sabor: ")
helado2= input("ingrese su segundo sabor: ")
helado3= input("ingrese su tercer sabdor: ")

mensaje = "Hola Aqui tiene su helado de: " + helado1 + " ,"+ helado2 + " y " + helado3 

print (mensaje)
