#################################################################################################
#programador:Garcia helen                                                                       #
#email:garcia.helen14@yahoo.com.ar                                                              #
#celular: 36776693                                                                              #
#################################################################################################
#fecha:04/08/2022                                                                               #
#lenguaje: python                                                                               # 
#version : 3.10.4                                                                               #
#################################################################################################   
#curso:programacion python en  ADAITW
#objetivo: Crear un programa que pida ingresar una cantidad en minutos mediante un y muestre un mensaje con el resultado de la conversión en segundos.

cantidad = int(input("ingrese una cantidad en minutos: "))
segundos = cantidad *60 
print(cantidad ,"minutos son", segundos ,"segundos" )
