####################################################################################
#programadora: Helen Garcia                                                        #
#e-mail: garcia.helen14@yahoo.com.ar                                               #
#celular: 156379648                                                                #
####################################################################################
#fecha:04/08/2022
#lenguaje:python
#version:3.10.4
#curso: programacion python en ADAITW 
 
 
#obejtivo: Crear un programa que pida ingresar una cantidad de días y muestre un mensaje con el resultado de la conversión en segundos.

dias = int(input(" ingrese la cantidad de dias: "))
segundos = dias * 86400 
print (dias," dia tiene ", segundos, " segundos " )