####################################################################################
#programadora: Helen Garcia                                                        #
#e-mail: garcia.helen14@yahoo.com.ar                                               #
#celular: 156379648                                                                #
####################################################################################
#fecha:04/08/2022
#lenguaje:python
#version:3.10.4
#curso: programacion python en ADAITW 
#objetivo:Crear un programa que pida ingresar una cantidad de kilómetros y
#muestre un mensaje con el resultado de la conversión en millas

kilometros = int(input("Ingrese la cantidad de kilometros:"))
millas = kilometros * 0.621371
print ( kilometros, "kilometro es " ,millas , "millas")